### ISSUE TITLE
Expired SSL certificate

### ISSUE THREAD

**Issue by adamjstewart** [phelber/EuroSAT#10]
The SSL certificate for https://madm.dfki.de/files/sentinel/EuroSATallBands.zip and https://madm.dfki.de/files/sentinel/EuroSAT.zip has expired, meaning that the dataset can no longer be downloaded. Can someone update this SSL cert?

**Comment by NourSoltani** [comment]
excuse me..Although that, I think you still can download it..
https://madm.dfki.de/files/sentinel/EuroSATallBands.zip
https://madm.dfki.de/files/sentinel/EuroSAT.zip
Just click on: [Proceed to madm.dfki.de (unsafe)]

**Comment by adamjstewart** [comment]
Unsafe is... not safe. This also breaks downloads for libraries that provide the dataset ([TorchGeo](https://torchgeo.readthedocs.io/en/latest/api/datasets.html#eurosat), [torchvision](https://pytorch.org/vision/stable/generated/torchvision.datasets.EuroSAT.html), [TensorFlow](https://www.tensorflow.org/datasets/catalog/eurosat)). Downloads with wget or curl break (unless you add flags to ignore missing SSL certs). Basically, I can get the dataset if I really need it, but a lot of software libraries are broken until the SSL cert is updated or the dataset is rehosted elsewhere.

**Comment by calebrob6** [comment]
@phelber is it possible for us to rehost the EuroSAT downloads somewhere else (huggingface / zenodo)? I was not able to find a license.

**Comment by phelber** [comment]
@calebrob6 In general, Sentinel data is free and open to the public under EU law ([Copernicus Sentinel Data Terms and Conditions](https://sentinel.esa.int/documents/247904/690755/Sentinel_Data_Legal_Notice)). I want the EuroSAT dataset to be as freely available as possible. Therefore, no further restrictions on its use or distribution apply from my side. Please feel free to host the dataset on a platform of your choice.

**Comment by phelber** [comment]
> Unsafe is... not safe. This also breaks downloads for libraries that provide the dataset ([TorchGeo](https://torchgeo.readthedocs.io/en/latest/api/datasets.html#eurosat), [torchvision](https://pytorch.org/vision/stable/generated/torchvision.datasets.EuroSAT.html), [TensorFlow](https://www.tensorflow.org/datasets/catalog/eurosat)). Downloads with wget or curl break (unless you add flags to ignore missing SSL certs). Basically, I can get the dataset if I really need it, but a lot of software libraries are broken until the SSL cert is updated or the dataset is rehosted elsewhere.

This is indeed not good. I have informed the administrator about the expired certificate and asked for a renewal. However, in general I think it is a better idea to host the dataset on another platform that provides adequate data provisioning, as suggested by @calebrob6.

**Comment by adamjstewart** [comment]
Thanks, we redistributed on https://huggingface.co/datasets/torchgeo/eurosat if anyone else needs it. An added bonus is that the download is slightly faster: 3m 7s instead of 4m 11s.

I'll leave this issue open so we can track the expired cert.

**Comment by adamjstewart** [comment]
> Therefore, no further restrictions on its use or distribution apply from my side.

It may be a good idea to add a LICENSE file to this repository so this is clearly documented.

**Comment by adamjstewart** [comment]
Also added the RGB-only download and a tiny version of the MS download containing only 100 images, both on Hugging Face at the link above if anyone needs them.

**Comment by phelber** [comment]
The SSL certificate does not seem to have been updated yet. Unfortunately, I have no control over the SSL certificate update process with the original hoster. I decided to host the dataset with Zenodo and would close the issue here.

**Comment by adamjstewart** [comment]
Zenodo has pretty abysmal download speeds, I've found Hugging Face to be roughly 20x faster for the datasets and pre-trained models we use in TorchGeo.
