### ISSUE TITLE
GPS coordinates for each observation point

### ISSUE THREAD

**Issue by tchambon** [phelber/EuroSAT#2]
Thank you for your great paper and dataset!

I would like to know if you have published the GPS coordinate of each observation point? I can't find this metadata in the tiff files. Is it in another file?

**Comment by logsanand** [comment]
Thank you for the dataset!.
         I would like to know the labelling platform used to annotate the eurosat dataset.

**Comment by phelber** [comment]
The released patches are all georeferenced. The multispectral version is provided in GeoTIFF format.
