### ISSUE TITLE
Which product type did you use for Sentinel-2?

### ISSUE THREAD

**Issue by issa-tingzon** [phelber/EuroSAT#5]
Did you use Sentinel-2A Level1-C or Level2-A? 
I think the only difference is that the latter is atmospherically corrected.

**Comment by mMagmer** [comment]
Quotes from EuroSat paper :
* the proposed dataset has not received atmospheric correction. This can result in images with a color cast.
* Bands with a lower spatial resolution have been Up-Sampled to 10 meters per pixel using cubic-spline interpolation
and B08A band placed at 13th channel (this is not in the paper) and I think they've used level1-c data .

**Comment by phelber** [comment]
Thanks for the answer, @mMagmer. I will close this issue.
