### ISSUE TITLE
A question about makeing RGB version data from MS data

### ISSUE THREAD

**Issue by ErenTuring** [phelber/EuroSAT#6]
Thank you for sharing this great dataset!

When using the three bands of B04, B03 and B02 in MS to make the data of RGB version, I am wondering how the pixel values (DN) of the two versions of data were mapped?
I checked the samples of MS version and RGB version corresponding to the same region. Taking the Red band as an example, the DN value of the MS version sample is not linearly mapped to the RGB version.

Besides, for MS version data, what's  your normlization stragery when training with CNNs?  Specifically, MS data with pixel values ranging from 0 to 6000 is directly subtracted by A divided by B, where A is a fix number for all 13 bands and whole dataset？

**Comment by mMagmer** [comment]
@ErenTuring , i think you can use `(ms[1:4][::-1]*2.5/10000).clip(0,1)` ,it is fairly colse

**Comment by johannespetrat** [comment]
Thanks for looking into this @ErenTuring and @mMagmer . I'm facing the same issue now and haven't been able to reproduce the RGB EuroSAT images from the multiband images. Scaling the multiband images in the way you're suggesting doesn't exactly reproduce the images. Issue #1 also seems to relate to this. Did you find a solution @ErenTuring ?

**Comment by phelber** [comment]
I've added the information in the README.md.
