### ISSUE TITLE
Order of the Bands of the MS dataset

### ISSUE THREAD

**Issue by mkutuk** [phelber/EuroSAT#7]
What is the order of the bands of the MS dataset? Is the 8A band placed as the 13th band? Thank you very much for this great dataset.

**Comment by mMagmer** [comment]
yes , i think the order is based on sentinel-2 playground website
"b1" , "b2" , "b3" , "b4", "b5","b6" , "b7" , "b8" , "b9" ,"b10" , "b11"  , "b12", "b8a"
[https://apps.sentinel-hub.com/sentinel-playground/?source=S2&lat=50.93630953645777&lng=-0.09827613830566406](url)
