### ISSUE TITLE
data is not geo-referenced or dated 

### ISSUE THREAD

**Issue by bardout** [phelber/EuroSAT#8]
The ReadMe and paper say it is. The original S2 products are geo-referenced and dated, but the list of the used granules are not provided. but the archive only contains numbered jpeg files, named and classified by the land use class. 

Do you have a table indicating the for each filename: the date of capture and coordinates of center or uperright & bottomleft corners ? either in absolute WGS84 or a projection valid on the european zone ? Thank you.

**Comment by y-vasyunin** [comment]
I support this question, as it is also important for me to restore the original IDs of the used Copernicus images.

**Comment by mMagmer** [comment]
@bardout as mentioned in #2  The multispectral version is provided in GeoTIFF format. you can use `gdalinfo {filename}` to see the coordinates.

**Comment by phelber** [comment]
Thanks for the reply, @mMagmer. I will close this issue.
